version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch
    hostname: elasticsearch
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/elastic-data:/usr/share/elasticsearch/data
      - ./elasticsearch/elastic-backup:/usr/share/elasticsearch/backup
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - single_elastic_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://elasticsearch:9200/_cluster/health || exit 1"]
      interval: 30s
      retries: 10
      timeout: 10s
    restart: unless-stopped


  kibana-single:
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: kibana-single
    hostname: kibana
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
    ports:
      - "5601:5601"
    networks:
      - single_elastic_network
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    
    
networks:
  single_elastic_network:
    driver: bridge

